---
- name: 'ASPNetMVC playbook'
  hosts: default
  vars: 
    ansible_python_interpreter: "/usr/bin/python2.7"

  tasks:
    - name: Installing ASPNetMVC
      win_chocolatey:
        name: aspnetmvc.install
        state: present
